### ISSUE TITLE
[BUG] Queue empty during song change when playing a playlist

### ISSUE THREAD

**Issue by poohcom1** [Among-Suss/groov-in-c#14] opened 2021-09-28 06:38 UTC
**Describe the bug**
For a short period of time when the song in a playlist is changing, using the `-queue` command outputs "No song playing".

**To Reproduce**
1. Queue a playlist
2. Use the skip command
3. Use the queue command

**Expected behavior**
Queue should show regardless

**Additional context**
This is probably due to the playlist's partial object system, maybe the empty queue check doesn't account for partial objects?

**Comment by TanapTheTimid** [comment] 2021-09-28 08:28
This is because the -queue command checks (vgt->media->playing). and (vgt->media->playing) is set to false right after song finishes playing and then set to true again when a new song starts playing. The gap caused by ytdl lookup lies in a section where (vgt->media->playing) is false. I think you can safely remove the check for (vgt->media->playing) in -queue and shouldn't break anything.

**Comment by TanapTheTimid** [comment] 2021-09-28 08:41
Fixed by b567f65534bdbcf2d2e0afd01826d78e74f23764

**Closed by TanapTheTimid** 2021-09-28 08:41 UTC
Labels: bug
